version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: gomod
    directory: "/tools"
    schedule:
      interval: "daily"

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: "daily"
