%% @backgroundColor(Gray)

sequenceDiagram
	actor Admin as Admin
	participant Trip as TripAdvisor
	participant DB as POIDataBase

	Admin->>+Trip: addPOI(accessToken, poi)

		Trip->>Trip: verifyAuthorization(accessToken)
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: (ErrNotAuthorized, nil)
			end
		else Authorized
			Trip->>Trip: verifyPOI(poi)
		end

		alt Invalid POI
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: (ErrInvalidPOI, nil)
			end

		else Valid POI
			Trip->>+DB: insertPOI(poi)
		end

		alt POI found
			rect rgba(255, 0, 0, 0.3)
				DB-->>Trip: (ErrAlreadyExists, existingPOI)
				Trip-->>Admin: (ErrPOIAlreadyExists, existingPOI)
			end
		else POI not found
			DB-->>-Trip: (nil, nil)
			Trip-->>-Admin: (nil, nil)
		end
