%% @backgroundColor(Gray)

sequenceDiagram
	actor Admin as Admin
	participant Trip as TripAdvisor
	participant DB as POIDataBase

	Admin->>+Trip: findPOIs(accessToken, poiOpts)

		Trip->>Trip: verifyAuthorization(accessToken)
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: (ErrNotAuthorized, nil)
			end
		else Authorized
			Trip->>Trip: verifyPOIOpts(poiOpts)
		end

		alt Invalid poiOpts
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: ErrInvalidPOIOpts, nil
			end

		else Valid poiOpts
			Trip->>+DB: findPOIs(poiOpts)
		end


		DB-->>-Trip: List<POI>
		Trip-->>-Admin: nil, List<POI>
