sequenceDiagram
	actor Admin as Admin/Client
	participant Trip as TripAdvisor
	participant DB as POIDataBase

	Admin->>+Trip: getPOI(accessToken, id)
	Note over Admin,Trip: GET api/v1/places/{id}

		Trip->>Trip: verifyAuthentication(accessToken)
		alt Not authenticated
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 16: UNAUTHENTICATED
				Note over Admin,Trip: 401: Unauthorized
			end
		else Authenticated
			Trip->>Trip: verifyAuthorization(accessToken.payload)
		end
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 7: PERMISSION_DENIED
				Note over Admin,Trip: 403: Forbidden
			end
		else Authorized
			Trip->>+DB: getPOI(id)
		end

		alt Not found
			rect rgba(255, 0, 0, 0.3)
				DB-->>Trip: NOT_FOUND
				Trip-->>Admin: 5: NOT_FOUND
				Note over Admin,Trip: 404: Not Found
			end
		else Found
			DB-->>-Trip: (OK, POI)
			Trip-->>-Admin: (0: OK, POI)
			Note over Admin,Trip: (200: OK, POI)
		end
