%% @backgroundColor(Gray)

sequenceDiagram
	actor Client as Client
	participant Trip as TripAdvisor
	participant DB as POIDataBase
    participant Map as MapAPI

	Client->>+Trip: findPOIs(accessToken, poiOpts, GeoLoc)

		Trip->>Trip: verifyAuthorization(accessToken)
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: (ErrNotAuthorized, nil)
			end
		else Authorized
			Trip->>Trip: verifyPOIOpts(poiOpts)
		end

		alt Invalid poiOpts
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: ErrInvalidPOIOpts, nil
			end
		else Valid poiOpts
			Trip->>+DB: findPOIs(poiOpts)
		end

        alt POIs not found
		rect rgba(255, 0, 0, 0.3)
                DB-->>Trip: nil
                Trip-->>Client: ErrNoSuitablePOIs, nil
            end
        else POIs found
            DB-->>-Trip: List<POI>
        end

        Trip->>+Map: createRoute(GeoLoc, List<POI>)

		alt Route creation error
			rect rgba(255, 0, 0, 0.3)
                Map-->>Trip: nil
                Trip-->>Client: ErrRouteCreation, nil
            end
        else Route created
		    Map-->>-Trip: List<POI>
			Trip-->>-Client: nil, List<POI>
        end     


