%% @backgroundColor(Gray)

sequenceDiagram
	actor Admin as Admin
	participant Trip as TripAdvisor
	participant DB as POIDataBase

	Admin->>+Trip: removePOI(accessToken, poiID)

		Trip->>Trip: verifyAuthorization(accessToken)
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: ErrNotAuthorized
			end
		else Authorized
			Trip->>+DB: removePOIByID(poiID)
		end



		alt POI not found
			rect rgba(255, 0, 0, 0.3)
				DB-->>Trip: ErrNotFound
				Trip-->>Admin: ErrPOINotFound
			end
		else POI found
			DB-->>-Trip: nil
			Trip-->>-Admin: nil
		end
