sequenceDiagram
	actor Client as Client
	participant Trip as TripAdvisor
	participant DB as POICache
	participant Map as MapAPI


	Client->>+Trip: searchPOI(searchOptions, continuationToken)<br/>Authorization: Bearer (accessToken)
	Note over Client,Trip: GET api/v1/places<br/>Authorization: Bearer (accessToken)<br/>Body: ContinuationToken: (continuationToken)

		Trip->>Trip: verifyAuthentication(accessToken)
		alt Not authenticated
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: Status code: 16::UNAUTHENTICATED
				Note over Client,Trip: Status code: 401::Unauthorized
			end
		else Authenticated
			Trip->>Trip: verifyAuthorization(accessToken.payload)
		end
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: Status code: 7::PERMISSION_DENIED
				Note over Client,Trip: Status code: 403::Forbidden
			end
		else Authorized
			Trip->>Trip: verifysearchOptions(searchOptions)
		end

		alt Invalid searchOptions
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: Status code: 3::INVALID_ARGUMENT
				Note over Client,Trip: Status code: 400::Bad Request
			end

		else Valid searchOptions
			loop for category in searchOptions.categories
				Trip->>+DB: getPOI(category)
				alt Cache miss
					rect rgba(255, 165, 0, 0.6)
						DB-->>Trip: Status code: 5::NOT_FOUND
						Trip->>+Map: getPOI(category)
						Map-->>-Trip: List<POI><br/>Status code: 0::OK
						Trip-)DB: storePOI(List<POI>)
					end
				else Cache hit
					DB-->>-Trip: List<POI><br/>Status code: 0::OK
				end
				Trip-)Trip: List<POI>.filter(searchOptions)
			end
		end
		Trip->>Trip: List<POI>.sub(continuationToken.List<POI>)
		Trip-->>-Client: List<POI>?<br/>Status code: 0::OK
		Note over Client,Trip: List<POI>?<br/>Status code: 200::OK
