sequenceDiagram
	actor Client as Client
	participant Trip as TripAdvisor
	participant DB as POICache


	Client->>+Trip: searchPOI(searchOptions)<br/>Authorization: Bearer (accessToken)
	Note over Client,Trip: GET api/v1/places<br/>Authorization: Bearer (accessToken)

		Trip->>Trip: verifyAuthentication(accessToken)
		alt Not authenticated
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: Status code: 16::UNAUTHENTICATED
				Note over Client,Trip: Status code: 401::Unauthorized
			end
		else Authenticated
			Trip->>Trip: verifyAuthorization(accessToken.payload)
		end
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: Status code: 7::PERMISSION_DENIED
				Note over Client,Trip: Status code: 403::Forbidden
			end
		else Authorized
			Trip->>Trip: verifysearchOptions(searchOptions)
		end

		alt Invalid searchOptions
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Client: Status code: 3::INVALID_ARGUMENT
				Note over Client,Trip: Status code: 400::Bad Request
			end

		else Valid searchOptions
			Trip->>+DB: getPOI(searchOptions)
			DB-->>-Trip: List<POI>?
			Trip-->>-Client: List<POI>?<br/>Status code: 0::OK
			Note over Client,Trip: List<POI>?<br/>Status code: 200::OK
		end
