sequenceDiagram
	actor Admin as Admin
	participant Trip as TripAdvisor
	participant DB as POIDataBase

	Admin->>+Trip: searchPOI(accessToken, searchOpts)
	Note over Admin,Trip: GET api/v1/places

		Trip->>Trip: verifyAuthentication(accessToken)
		alt Not authenticated
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 16: UNAUTHENTICATED
				Note over Admin,Trip: 401: Unauthorized
			end
		else Authenticated
			Trip->>Trip: verifyAuthorization(accessToken.payload)
		end
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 7: PERMISSION_DENIED
				Note over Admin,Trip: 403: Forbidden
			end
		else Authorized
			Trip->>Trip: verifysearchOpts(searchOpts)
		end

		alt Invalid searchOpts
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 3: INVALID_ARGUMENT
				Note over Admin,Trip: 400: Bad Request
			end

		else Valid searchOpts
			Trip->>+DB: getPOI(searchOpts)
		end


		DB-->>-Trip: List<POI>?
		Trip-->>-Admin: (0: OK, List<POI>?)
		Note over Admin,Trip: (200: OK, List<POI>?)
