sequenceDiagram
	actor Admin as Admin
	participant Trip as TripAdvisor
	participant DB as POIDataBase

	Admin->>+Trip: updatePOI(accessToken, poi)
	Note over Admin,Trip: PUT api/v1/places/{id}

		Trip->>Trip: verifyAuthentication(accessToken)
		alt Not authenticated
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 16: UNAUTHENTICATED
				Note over Admin,Trip: 401: Unauthorized
			end
		else Authenticated
			Trip->>Trip: verifyAuthorization(accessToken.payload)
		end
		alt Not authorized
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 7: PERMISSION_DENIED
				Note over Admin,Trip: 403: Forbidden
			end
		else Authorized
			Trip->>Trip: verifyPOI(poi)
		end


		alt Invalid POI
			rect rgba(255, 0, 0, 0.3)
				Trip-->>Admin: 3: INVALID_ARGUMENT
				Note over Admin,Trip: 400: Bad Request
			end
		else Valid POI
			Trip->>+DB: updatePOIByID(poi.ID, poi)
		end

		alt POI not found
			rect rgba(255, 0, 0, 0.3)
				DB-->>Trip: NOT_FOUND
				Trip-->>Admin: 5: NOT_FOUND
				Note over Admin,Trip: 404: Not Found
			end
		else POI found & updated
			DB-->>-Trip: (OK, updatedPOI)
			Trip-->>-Admin: (0: OK, updatedPOI)
			Note over Admin,Trip: (200: OK, updatedPOI)
		end
