version: '3.9'

services:

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017

  afterwork-backend:
    build: ../.
    image: afterwork:latest
    container_name: "afterwork-backend"
    restart: always
    environment:
      - GIN_MODE=release
    ports:
      - 9090:9090
    depends_on:
      - mongodb
