name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GO_VERSION: "1.20"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          # https://github.com/actions/setup-go#supported-version-syntax
          # ex:
          # - 1.18beta1 -> 1.18.0-beta.1
          # - 1.18rc1 -> 1.18.0-rc.1
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [golangci-lint]
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          # https://github.com/actions/setup-go#supported-version-syntax
          # ex:
          # - 1.18beta1 -> 1.18.0-beta.1
          # - 1.18rc1 -> 1.18.0-rc.1
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [go fmt]
        run: |
          go fmt ./...
          git diff --exit-code

  go-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          # https://github.com/actions/setup-go#supported-version-syntax
          # ex:
          # - 1.18beta1 -> 1.18.0-beta.1
          # - 1.18rc1 -> 1.18.0-rc.1
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [go vet]
        run: |
          go vet ./...

  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [typos]
        uses: crate-ci/typos@v1.14.12
        with:
          config: .typos.toml

  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        hook_id: [
          trailing-whitespace,
          end-of-file-fixer,
          check-yaml,
          detect-private-key
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Run [${{ matrix.hook_id }}]
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: ${{ matrix.hook_id }} --all-files
