name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GO_VERSION: "1.20"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          # https://github.com/actions/setup-go#supported-version-syntax
          # ex:
          # - 1.18beta1 -> 1.18.0-beta.1
          # - 1.18rc1 -> 1.18.0-rc.1
          go-version: ${{ env.GO_VERSION }}
      - name: Lint code
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check [typos]
        uses: crate-ci/typos@v1.14.9
        with:
          config: .typos.toml

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Check [trailing-whitespace]
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: trailing-whitespace --all-files

      - name: Check [end-of-file-fixer]
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: end-of-file-fixer --all-files

      - name: Check [check-yaml]
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: check-yaml --all-files

      - name: Check [detect-private-key]
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: detect-private-key --all-files
